# Generated by Django 3.0.5 on 2020-04-22 16:18

import core.custom.model_fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_currentuser.db.models.fields
import django_currentuser.middleware
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Creation date')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active ?')),
                ('first_name', core.custom.model_fields.LowerCharField(max_length=50, verbose_name='First name')),
                ('last_name', core.custom.model_fields.LowerCharField(max_length=50, verbose_name='Last name')),
                ('email', models.EmailField(max_length=120, verbose_name='Email')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Biography')),
                ('profile_picture', models.ImageField(upload_to='profile/%Y/%m/%d', verbose_name='Profile picture')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='Birthday')),
                ('twitter', core.custom.model_fields.LowerCharField(blank=True, max_length=120, null=True, verbose_name='Twitter Account')),
                ('linkedin', core.custom.model_fields.LowerCharField(blank=True, max_length=120, null=True, verbose_name='LinkedIn Account')),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('P', 'Private')], max_length=1, verbose_name='Gender')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_author_authors', to=settings.AUTH_USER_MODEL)),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_by_author_authors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
