# Generated by Django 3.0.5 on 2020-04-22 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='profile_picture',
            new_name='picture',
        ),
        migrations.RemoveField(
            model_name='author',
            name='email',
        ),
    ]
