# Generated by Django 3.0.5 on 2020-04-22 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0002_auto_20200422_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='picture',
            field=models.ImageField(upload_to='authors/%Y/%m/%d', verbose_name='Profile picture'),
        ),
    ]
