# Generated by Django 3.0.5 on 2020-04-30 18:33

import core.custom.model_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0002_auto_20200430_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='name',
            field=core.custom.model_fields.LowerCharField(max_length=250, verbose_name='Name'),
        ),
    ]
