# Generated by Django 3.0.5 on 2020-04-22 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0003_auto_20200422_1624'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'Author', 'verbose_name_plural': 'Authors'},
        ),
    ]
