# Generated by Django 3.0.5 on 2020-04-30 01:40

import core.custom.model_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0004_auto_20200422_1801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='author',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='author',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='author',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='author',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='author',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='author',
            name='twitter',
        ),
        migrations.AddField(
            model_name='author',
            name='name',
            field=core.custom.model_fields.LowerCharField(default=1, max_length=120, verbose_name='Name'),
            preserve_default=False,
        ),
    ]
