version: "3.7"

services:
  db:
    image: postgres:12
    container_name: postgres_books
    hostname: postgres_books
    environment:
      - POSTGRES_DB=$DB_NAME
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
    ports:
      - "$DB_PORT:5432"
    volumes:
      - ./books_backup.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_books_data:/var/lib/postgresql/data/
volumes:
  postgres_books_data:
