version: "3.7"

services:
  db:
    image: "postgres:12"
    container_name: postgres_books
    hostname: postgres_books
    environment:
      - POSTGRES_DB=books
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
    ports:
      - "$DB_PORT:5432"
    volumes:
      - postgres_books_data:/var/lib/postgresql/data/

volumes:
  postgres_books_data:
