version: "3.7"

services:
  backend:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.app
    image: backend
    hostname: backend
    container_name: backend
    command: gunicorn book_store.wsgi -b 0.0.0.0:8000
    links:
      - db
    volumes:
      - static-files:/static/

  nginx:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.nginx
    hostname: nginx
    image: nginx
    container_name: nginx
    ports:
      - 8001:80
    volumes:
      - static-files:/static/
    links:
      - backend

  frontend:
    build:
      context: ../frontend
      dockerfile: ./docker/Dockerfile.react
    image: frontend
    hostname: frontend
    container_name: frontend
    ports:
      - 80:80
    links:
      - backend

  db:
    image: postgres:12
    container_name: postgres_books
    hostname: postgres_books
    environment:
      - POSTGRES_DB=$DB_NAME
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
    ports:
      - "$DB_PORT:5432"
    volumes:
      - ./books_backup.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_books_data:/var/lib/postgresql/data/
volumes:
  postgres_books_data:
  static-files:
