# Generated by Django 3.0.5 on 2020-04-30 17:53

import core.custom.model_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_auto_20200430_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='label',
            field=core.custom.model_fields.TitleCharField(max_length=80, unique=True, verbose_name='Label'),
        ),
    ]
