# Generated by Django 3.0.5 on 2020-04-22 16:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_currentuser.db.models.fields
import django_currentuser.middleware


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('category', '0003_auto_20200420_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='created_by',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_category_categorys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='category',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Creation date'),
        ),
        migrations.AlterField(
            model_name='category',
            name='updated_by',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_by_category_categorys', to=settings.AUTH_USER_MODEL),
        ),
    ]
