# Generated by Django 3.0.5 on 2020-04-30 15:43

import core.custom.model_fields
from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Creation date')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active ?')),
                ('title', core.custom.model_fields.TitleCharField(max_length=250, verbose_name='Title')),
                ('subtitle', core.custom.model_fields.TitleCharField(max_length=250, verbose_name='Sub-Title')),
                ('isbn', core.custom.model_fields.UpperCharField(max_length=30, verbose_name='ISBN')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails/%Y/%m/%d', verbose_name='Thumbnail')),
                ('language', models.CharField(default='en', max_length=2, verbose_name='Language')),
                ('authors', models.ManyToManyField(related_name='books', to='author.Author')),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
            },
        ),
    ]
