# Generated by Django 3.0.5 on 2020-04-30 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20200430_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='thumbnail',
            field=models.URLField(blank=True, max_length=250, null=True, verbose_name='Thumbnail'),
        ),
    ]
