# Generated by Django 3.0.5 on 2020-04-30 18:44

import core.custom.model_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_auto_20200430_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=core.custom.model_fields.TitleCharField(blank=True, max_length=250, null=True, verbose_name='Publisher'),
        ),
        migrations.AlterField(
            model_name='book',
            name='subtitle',
            field=core.custom.model_fields.TitleCharField(blank=True, max_length=250, null=True, verbose_name='Sub-Title'),
        ),
    ]
