# Generated by Django 3.0.5 on 2020-04-22 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0003_auto_20200422_1624'),
        ('book', '0005_auto_20200422_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(related_name='books', to='author.Author'),
        ),
    ]
