# Generated by Django 3.0.5 on 2020-04-30 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_book_pages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='subtitle',
            field=models.TextField(blank=True, null=True, verbose_name='Sub-Title'),
        ),
    ]
