# Generated by Django 3.0.5 on 2020-05-01 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_auto_20200430_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(default='en', max_length=10, verbose_name='Language'),
        ),
    ]
