# Generated by Django 3.0.5 on 2020-04-30 01:33

import core.custom.model_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_book_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='book',
        ),
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=core.custom.model_fields.UpperCharField(default=1, max_length=30, verbose_name='ISBN'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='subtitle',
            field=core.custom.model_fields.TitleCharField(default=1, max_length=250, verbose_name='Sub-Title'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=core.custom.model_fields.TitleCharField(max_length=250, verbose_name='Title'),
        ),
    ]
