# Generated by Django 3.0.6 on 2020-05-21 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0012_book_avg_ratings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-raters'], 'verbose_name': 'Book', 'verbose_name_plural': 'Books'},
        ),
        migrations.AddIndex(
            model_name='userratings',
            index=models.Index(fields=['user_id'], name='book_userra_user_id_6a71d4_idx'),
        ),
    ]
