export default {
  LOAD_BOOKS_SUCCESS: "LOAD_BOOKS_SUCCESS",
  LOAD_USER_PREF_BOOKS_SUCCESS: "LOAD_USER_PREF_BOOKS_SUCCESS",
  LOAD_RATED_BOOKS_SUCCESS: "LOAD_RATED_BOOKS_SUCCESS",
  RATE_BOOK_SUCCESS: "RATE_BOOK_SUCCESS",
  GET_BOOK_BY_ID_SUCCESS: "GET_BOOK_BY_ID_SUCCESS",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  START_API_CALL: "START_API_CALL",
};
