# Generated by Django 3.0.6 on 2020-05-21 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['id'], name='users_custo_id_b28d27_idx'),
        ),
    ]
